<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>

    <groupId>ai-devops-agent-platform</groupId>
    <artifactId>ai-devops-agent-platform</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>ai-devops-agent-platform</name>
    <description>AI DevOps 平台聚合工程</description>

    <properties>
        <java.version>26</java.version>
    </properties>

    <modules>
        <module>iam</module>
        <module>project-management</module>
        <module>application</module>
        <module>mcp</module>
    </modules>
</project>
