CREATE TABLE pl_pipelines (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    project_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    current_version_no INT NOT NULL,
    created_by CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pl_pipelines_project_name (project_id, name),
    KEY idx_pl_pipelines_tenant_project (tenant_id, project_id),
    CONSTRAINT fk_pl_pipelines_project FOREIGN KEY (project_id) REFERENCES pm_projects(id),
    CONSTRAINT fk_pl_pipelines_tenant FOREIGN KEY (tenant_id) REFERENCES iam_tenants(id),
    CONSTRAINT fk_pl_pipelines_created_by FOREIGN KEY (created_by) REFERENCES iam_users(id),
    CONSTRAINT chk_pl_pipelines_version CHECK (current_version_no >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE pl_pipeline_versions (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    pipeline_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    version_no INT NOT NULL,
    yaml_content MEDIUMTEXT NOT NULL,
    content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    repository_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    repository_version_no INT NOT NULL,
    source_default_branch VARCHAR(255) NULL,
    created_by CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pl_pipeline_versions_pipeline_version (pipeline_id, version_no),
    KEY idx_pl_pipeline_versions_repository (repository_id),
    CONSTRAINT fk_pl_pipeline_versions_pipeline FOREIGN KEY (pipeline_id) REFERENCES pl_pipelines(id) ON DELETE CASCADE,
    CONSTRAINT fk_pl_pipeline_versions_repository FOREIGN KEY (repository_id) REFERENCES pm_repositories(id),
    CONSTRAINT fk_pl_pipeline_versions_created_by FOREIGN KEY (created_by) REFERENCES iam_users(id),
    CONSTRAINT chk_pl_pipeline_versions_no CHECK (version_no >= 1),
    CONSTRAINT chk_pl_pipeline_versions_repository_version CHECK (repository_version_no >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE pl_pipeline_steps (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    pipeline_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    stage_name VARCHAR(128) NOT NULL,
    stage_sequence_no INT NOT NULL,
    step_id VARCHAR(128) NOT NULL,
    step_sequence_no INT NOT NULL,
    plugin_name VARCHAR(128) NOT NULL,
    plugin_version VARCHAR(64) NOT NULL,
    input_json MEDIUMTEXT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pl_pipeline_steps_version_step (pipeline_version_id, step_id),
    UNIQUE KEY uk_pl_pipeline_steps_version_sequence (pipeline_version_id, step_sequence_no),
    CONSTRAINT fk_pl_pipeline_steps_version FOREIGN KEY (pipeline_version_id) REFERENCES pl_pipeline_versions(id) ON DELETE CASCADE,
    CONSTRAINT chk_pl_pipeline_steps_sequence CHECK (stage_sequence_no >= 1 AND step_sequence_no >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE pl_runs (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    project_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    pipeline_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    pipeline_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    repository_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    repository_version_no INT NOT NULL,
    source_branch VARCHAR(255) NULL,
    source_commit VARCHAR(128) NULL,
    status VARCHAR(16) NOT NULL,
    idempotency_key VARCHAR(128) NULL,
    configuration_snapshot MEDIUMTEXT NOT NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(500) NULL,
    requested_by CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(3) NOT NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pl_runs_project_idempotency (project_id, idempotency_key),
    KEY idx_pl_runs_project_created (project_id, created_at),
    KEY idx_pl_runs_status_created (status, created_at),
    CONSTRAINT fk_pl_runs_pipeline FOREIGN KEY (pipeline_id) REFERENCES pl_pipelines(id),
    CONSTRAINT fk_pl_runs_pipeline_version FOREIGN KEY (pipeline_version_id) REFERENCES pl_pipeline_versions(id),
    CONSTRAINT fk_pl_runs_repository FOREIGN KEY (repository_id) REFERENCES pm_repositories(id),
    CONSTRAINT fk_pl_runs_requested_by FOREIGN KEY (requested_by) REFERENCES iam_users(id),
    CONSTRAINT chk_pl_runs_status CHECK (status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELED','TIMED_OUT')),
    CONSTRAINT chk_pl_runs_source CHECK (source_branch IS NOT NULL OR source_commit IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE pl_step_runs (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    pipeline_step_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    step_sequence_no INT NOT NULL,
    step_id VARCHAR(128) NOT NULL,
    plugin_name VARCHAR(128) NOT NULL,
    plugin_version VARCHAR(64) NOT NULL,
    input_json MEDIUMTEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    output_json MEDIUMTEXT NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(500) NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pl_step_runs_run_sequence (run_id, step_sequence_no),
    CONSTRAINT fk_pl_step_runs_run FOREIGN KEY (run_id) REFERENCES pl_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_pl_step_runs_step FOREIGN KEY (pipeline_step_id) REFERENCES pl_pipeline_steps(id),
    CONSTRAINT chk_pl_step_runs_status CHECK (status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','CANCELED','TIMED_OUT','SKIPPED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE pl_step_logs (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    step_run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    sequence_no INT NOT NULL,
    level VARCHAR(16) NOT NULL,
    message VARCHAR(4000) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pl_step_logs_step_sequence (step_run_id, sequence_no),
    CONSTRAINT fk_pl_step_logs_step_run FOREIGN KEY (step_run_id) REFERENCES pl_step_runs(id) ON DELETE CASCADE,
    CONSTRAINT chk_pl_step_logs_level CHECK (level IN ('INFO','WARN','ERROR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
