package devops.mcp.identity;

/** MCP 适配层对 Codex 暴露的稳定错误码，避免透传后端敏感细节。 */
public enum McpErrorCode {
    REGISTRATION_CANCELLED,
    REGISTRATION_FAILED,
    REGISTRATION_LINK_NOT_FOUND,
    LOGIN_LINK_NOT_FOUND,
    LOGIN_CANCELLED,
    LOGIN_FAILED,
    MCP_ELICITATION_UNAVAILABLE,
    CREDENTIAL_STORE_FAILED,
    BACKEND_UNAVAILABLE,
    NOT_LOGGED_IN,
    SESSION_EXPIRED,
    BACKEND_ACCESS_DENIED
}
